### ISSUE TITLE
Fix the atrocious code formatting.

### ISSUE THREAD

**Issue by hopeseekr** [ryantxr/slack-webhook#2]
In the past, have you

1. only worked on a team of 1?
2. worked with a very dysfunctional team? or
3. just started learning PHP?

You need to reformat your code.

Use php-cs-fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by ryantxr** [comment]
Somehow this file ended up with tabs instead of spaces for indentation.  I ran phpcs on it and it is better now. Thanks for noticing.
